name: Sync from Private Repo

on:
  schedule:
    - cron: '30 7 * * *'  # Runs every day at 1:30 PM Bangladesh time
  workflow_dispatch:       # Manual trigger option

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3
        with:
          path: public

      - name: Clone Private Repo
        run: |
          git clone https://x-access-token:${{ secrets.PRIVATE_REPO_PAT }}@github.com/asicoltd/cp-private-dump.git private

      - name: Copy New/Updated Files
        run: |
          rsync -av --ignore-existing private/ public/
          rsync -av --update private/ public/

      - name: Commit and Push Changes
        run: |
          cd public
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync from private repo" || echo "Nothing to commit"
          git push origin main
